import fs from 'node:fs/promises';
import path from 'node:path';

const rootDir = process.cwd();
const promptsDir = path.join(rootDir, 'prompts');
const outputFile = path.join(rootDir, 'src', 'lib', 'generated', 'prompts.ts');

function toCamelCase(value) {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((segment, index) => {
      const lower = segment.toLowerCase();
      if (index === 0) return lower;
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join('');
}

async function readPromptEntries() {
  const directoryEntries = await fs.readdir(promptsDir, { withFileTypes: true });
  const promptDirectories = directoryEntries.filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort();

  const entries = [];

  for (const directoryName of promptDirectories) {
    const promptPath = path.join(promptsDir, directoryName, 'prompt.txt');
    const content = await fs.readFile(promptPath, 'utf8');
    entries.push({ key: toCamelCase(directoryName), directoryName, content });
  }

  return entries;
}

async function build() {
  const entries = await readPromptEntries();

  if (entries.length === 0) {
    throw new Error('No prompt templates found under prompts/.');
  }

  const objectEntries = entries
    .map((entry) => `  ${JSON.stringify(entry.key)}: ${JSON.stringify(entry.content)}`)
    .join(',\n');

  const source = `// This file is generated by scripts/build-prompts.mjs.\n// Do not edit it directly. Edit prompts/**/prompt.txt instead.\n\nexport const promptTemplates = {\n${objectEntries}\n} as const;\n\nexport type PromptTemplateKey = keyof typeof promptTemplates;\n`;

  await fs.mkdir(path.dirname(outputFile), { recursive: true });
  await fs.writeFile(outputFile, source);
  console.log(`Generated ${entries.length} prompt templates at ${path.relative(rootDir, outputFile)}`);
}

build().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});